conf/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace="pages")),
    path('shop/', include('shop.urls', namespace='shop')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('recipies/', include('recipies.urls', namespace='recipies')),
    path('users/', include('users.urls', namespace='users'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from shop.views import product_list_view, product_detail_view

app_name = 'shop'

urlpatterns = [
    path('', product_list_view, name='product-list'),
    path('detail/<int:pk>', product_detail_view, name='detail')
]

shop/models.py
from django.db import models

from pages.models import BaseModel

class ProductModel(BaseModel):
    img = models.ImageField(upload_to='shop')
    name = models.CharField(max_length=50)
    price = models.FloatField()
    discount = models.FloatField()
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

shop/views.py
from django.shortcuts import render
from shop.models import ProductModel

product = ProductModel.objects.all()
context = {
    'product': product
}

def product_list_view(request):
    return render(request, 'shop/product-list.html', context)

def product_detail_view(request, pk):
    product = ProductModel.objects.filter(id=pk)
    if product is not None:
        context = {
            'product': product
        }
        return render(request, 'shop/product_detail.html', context)
    else:
        return render(request, 'pages/404.html')

templates/shop/product-list.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %}Shop{% endblock %}
{% block content %}
    <!-- Inne Page Banner Area Start Here -->
    <section class="inner-page-banner bg-common" data-bg-image="{% static 'img/figure/inner-page-banner1.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-area">
                        <h1>Our Shop Page</h1>
                        <ul>
                            <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>Shop Page</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Inne Page Banner Area End Here -->
    <!-- Shop Page Area Start Here -->
    <section class="shop-page-wrap padding-top-74 padding-bottom-50">
        <div class="container">
            <div class="row gutters-60">
                <div class="col-lg-8">
                    <div class="d-sm-flex justify-content-between align-items-center">
                        <div class="section-heading heading-dark">
                            <h2 class="item-heading">SHOWING 16-24 OF 50 RESULTS</h2>
                        </div>
                        <div class="filter-box">
                            <select class="select2" name="filter-by">
                                <option value="0">Breakfast</option>
                                <option value="1">Newest</option>
                                <option value="2">Top Sell</option>
                                <option value="3">Top Rated</option>
                                <option value="4">Price High</option>
                                <option value="5">Low Price</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        {% for shop in product %}
                        <div class="col-md-4 col-sm-6 col-12">
                            <div class="shop-box-layout1">
                                <div class="mask-item bg--accent">
                                    <div class="item-figure">
                                        <img src="{{ shop.img.url }}" alt="Product">
                                    </div>
                                    <ul class="action-items">
                                        <li>
                                            <a href="#">
                                                <i class="fas fa-shopping-cart"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fas fa-exchange-alt"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fas fa-heart"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="item-content">
                                    <h3 class="item-title"><a href="{% url "shop:detail" pk=shop.id %}">{{ shop.name }}</a></h3>
                                    <div class="item-price"><span class="currency">$</span>{{ shop.price }}</div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <ul class="pagination-layout1">
                        <li class="active">
                            <a href="#">1</a>
                        </li>
                        <li>
                            <a href="#">2</a>
                        </li>
                        <li>
                            <a href="#">3</a>
                        </li>
                        <li>
                            <a href="#">4</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-4 sidebar-widget-area sidebar-break-md">
                    <div class="widget">
                        <div class="section-heading heading-dark">
                            <h3 class="item-heading">CATEGORIES</h3>
                        </div>
                        <div class=" widget-search">
                            <div class="input-group stylish-input-group">
                                <input type="text" class="form-control" placeholder="Search product . . .">
                                <span class="input-group-addon">
                                    <button type="submit">
                                        <span class="flaticon-magnifying-glass" aria-hidden="true"></span>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="widget">
                        <div class="section-heading heading-dark">
                            <h3 class="item-heading">CATEGORIES</h3>
                        </div>
                        <div class="widget-categories">
                            <ul>
                                <li>
                                    <a href="#">BreakFast
                                        <span>25</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">Lunch
                                        <span>15</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">Pasta
                                        <span>22</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">Dinner
                                        <span>18</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">Dessert
                                        <span>36</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">Drinks
                                        <span>12</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">Fruits
                                        <span>05</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="widget">
                        <div class="section-heading heading-dark">
                            <h3 class="item-heading">TOP PRODUCTS</h3>
                        </div>
                        <div class="widget-top-product">
                            <ul class="block-list">
                                <li class="single-item">
                                    <div class="item-img">
                                        <a href="single-shop.html" class="item-icon"><i class="flaticon-plus-1"></i></a>
                                        <img src="{% static 'img/product/top-product1.jpg' %}" alt="Post">
                                    </div>
                                    <div class="item-content">
                                        <h4 class="item-title"><a href="#">Kitchen Product</a></h4>
                                        <div class="item-price"><span class="item-currency">$</span>15.00</div>
                                    </div>
                                </li>
                                <li class="single-item">
                                    <div class="item-img">
                                        <a href="single-shop.html" class="item-icon"><i class="flaticon-plus-1"></i></a>
                                        <img src="{% static 'img/product/top-product2.jpg' %}" alt="Post">
                                    </div>
                                    <div class="item-content">
                                        <h4 class="item-title"><a href="#">Kitchen Product</a></h4>
                                        <div class="item-price"><span class="item-currency">$</span>25.00</div>
                                    </div>
                                </li>
                                <li class="single-item">
                                    <div class="item-img">
                                        <a href="single-shop.html" class="item-icon"><i class="flaticon-plus-1"></i></a>
                                        <img src="{% static 'img/product/top-product3.jpg' %}" alt="Post">
                                    </div>
                                    <div class="item-content">
                                        <h4 class="item-title"><a href="#">Kitchen Product</a></h4>
                                        <div class="item-price"><span class="item-currency">$</span>29.00</div>
                                    </div>
                                </li>
                                <li class="single-item">
                                    <div class="item-img">
                                        <a href="single-shop.html" class="item-icon"><i class="flaticon-plus-1"></i></a>
                                        <img src="{% static 'img/product/top-product4.jpg' %}" alt="Post">
                                    </div>
                                    <div class="item-content">
                                        <h4 class="item-title"><a href="#">Kitchen Product</a></h4>
                                        <div class="item-price"><span class="item-currency">$</span>10.00</div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="widget">
                        <div class="widget-ad">
                            <a href="#"><img src="{% static 'img/figure/figure5.jpg' %}" alt="Ad" class="img-fluid"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Page Area End Here -->
{% endblock %}